const AS='assets/';
const heroes=[
 {id:'nezha',name:'哪吒·红莲',type:'神话机甲 · 爆发型',img:'nezha.png',hp:120,attack:17,ult:'红莲天火阵',ultDamage:49,color:10,desc:'伤害更高，大招召唤九重红莲'},
 {id:'optimus',name:'擎天圣',type:'变形机甲 · 守护型',img:'optimus.png',hp:145,attack:14,ult:'星辰领袖炮',ultDamage:42,color:205,desc:'生命更高，守护技能恢复更多'}
];
const stages=[
 {name:'星际前哨',bg:'bg-1.png',hp:82,atk:[8,12],label:'猎食形态',evolveAt:.46},
 {name:'蓝星都市',bg:'bg-2.png',hp:106,atk:[10,15],label:'装甲形态',evolveAt:.50},
 {name:'远古秘境',bg:'bg-3.png',hp:134,atk:[12,17],label:'暴走形态',evolveAt:.54},
 {name:'赤焰终局',bg:'bg-4.png',hp:172,atk:[14,20],label:'终极形态',evolveAt:.58}
];
const $=s=>document.querySelector(s); let hero=null,stage=0,hp=0,enemyHp=0,energy=0,busy=false,guard=false,music=false,evolved=false,enemyTurns=0;
const screens=['#selectScreen','#battleScreen','#resultScreen'];
function show(id){screens.forEach(s=>$(s).classList.toggle('active',s===id))}
function renderHeroes(){ $('#heroCards').innerHTML=heroes.map((h,i)=>`<button class="hero-card" data-i="${i}"><img src="${AS+h.img}" alt="${h.name}"><h3>${h.name}</h3><p>${h.type}</p><div class="stats" title="综合能力">${[0,1,2,3,4].map(n=>`<i class="${n<(i?5:4)?'on':''}"></i>`).join('')}</div></button>`).join(''); document.querySelectorAll('.hero-card').forEach(c=>c.onclick=()=>selectHero(+c.dataset.i))}
function selectHero(i){hero=heroes[i];document.querySelectorAll('.hero-card').forEach((c,n)=>c.classList.toggle('selected',n===i));$('#startBtn').disabled=false;$('#startBtn').textContent=`和${hero.name}一起出发`}
async function cutout(img){if(img.dataset.cutout)return;try{let source=new Image();source.src=img.src;await source.decode();let c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=source.naturalWidth;c.height=source.naturalHeight;x.drawImage(source,0,0);let d=x.getImageData(0,0,c.width,c.height),p=d.data;for(let i=0;i<p.length;i+=4){let lo=Math.min(p[i],p[i+1],p[i+2]),hi=Math.max(p[i],p[i+1],p[i+2]);if(lo>242&&hi-lo<13)p[i+3]=0;else if(lo>220&&hi-lo<16)p[i+3]=Math.min(p[i+3],(242-lo)*12)}x.putImageData(d,0,0);img.src=c.toDataURL('image/webp',.86);img.dataset.cutout='1'}catch(e){img.dataset.cutout='fallback'}}
function setSprite(selector,file){let img=$(`${selector} img`);img.dataset.cutout='';img.src=AS+file;img.onload=()=>cutout(img)}
function startStage(){const s=stages[stage];hp=hero.hp;enemyHp=s.hp;energy=0;guard=false;busy=false;evolved=false;enemyTurns=0;show('#battleScreen');$('#arena').style.backgroundImage=`linear-gradient(#07112a22,#05071855),url('${AS+s.bg}')`;$('#stageText').textContent=`第 ${stage+1} 关 / 4`;$('#stageName').textContent=s.name;$('#stars').textContent='★'.repeat(stage+1)+'☆'.repeat(3-stage);$('#heroName').textContent=hero.name;$('#enemyName').textContent=`暴虐霸王龙 · ${s.label}`;setSprite('#heroFighter',hero.img);setSprite('#enemyFighter','dino-1.png');$('#heroAvatar').style.backgroundImage=`url('${AS+hero.img}')`;$('.enemy-avatar').style.backgroundImage=`url('${AS+'dino-1.png'}')`;$('#evolutionAlert').classList.remove('danger');$('#evolutionAlert small').textContent='霸王龙生命低于一半会进入暴虐形态';$('#ultimateName').textContent=hero.ult;update();announce(`第 ${stage+1} 关`,s.name);playMusic()}
function update(){const s=stages[stage];$('#heroHp').style.width=`${Math.max(0,hp/hero.hp*100)}%`;$('#enemyHp').style.width=`${Math.max(0,enemyHp/s.hp*100)}%`;$('#energyBar').style.width=`${energy}%`;$('#heroHpText').textContent=`${Math.max(0,hp)} / ${hero.hp}`;$('#enemyHpText').textContent=`${Math.max(0,enemyHp)} / ${s.hp}`;$('#ultimateBtn').disabled=energy<100||busy;$('#ultHint').textContent=energy>=100?'能量已满 · 点击释放！':`还差 ${100-energy} 能量`;$('#attackBtn').disabled=busy;$('#guardBtn').disabled=busy}
function announce(a,b=''){let el=$('#announcement');el.innerHTML=`${a}<small style="display:block;font-size:.35em;color:#8eeaff">${b}</small>`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function particles(h=190,count=24){for(let i=0;i<count;i++){let p=document.createElement('i');p.className='particle';p.style.cssText=`left:${45+Math.random()*20}%;top:${38+Math.random()*25}%;--h:${h+Math.random()*100};--x:${(Math.random()-.5)*620}px;--y:${(Math.random()-.5)*420}px`;$('#fx').append(p);setTimeout(()=>p.remove(),1250)}}
function addFx(cls,life=1200){let f=document.createElement('i');f.className=cls;$('#fx').append(f);setTimeout(()=>f.remove(),life)}
function animAttack(ultimate=false){let me=$('#heroFighter'),foe=$('#enemyFighter');me.classList.add(ultimate?'ultimate-lunge':'attack');setTimeout(()=>{foe.classList.add('hit');addFx(ultimate?'burst':'slash');addFx(ultimate?'rainbow-ring':'impact-flash');if(ultimate){addFx('energy-beam',1500);addFx('ultimate-vignette',1500);setTimeout(()=>addFx('rainbow-ring'),260)}particles(hero.color,ultimate?85:20)},220);setTimeout(()=>{me.classList.remove('attack','ultimate-lunge');foe.classList.remove('hit')},ultimate?1200:760)}
function playerMove(kind){if(busy)return;busy=true;if(kind==='attack'){enemyHp-=hero.attack+Math.floor(Math.random()*6);energy=Math.min(100,energy+20);animAttack()}else if(kind==='guard'){guard=true;hp=Math.min(hero.hp,hp+(hero.id==='optimus'?20:14));energy=Math.min(100,energy+15);announce('能量护盾','本回合伤害减半');particles(180,18)}else{enemyHp-=hero.ultDamage+Math.floor(Math.random()*12);energy=0;animAttack(true);announce(hero.ult,'超能爆发！')}update();setTimeout(()=>{if(enemyHp<=0)win();else if(!evolved&&enemyHp<=stages[stage].hp*stages[stage].evolveAt)evolveEnemy();else enemyTurn()},kind==='ult'?1450:850)}
function evolveEnemy(){evolved=true;let s=stages[stage];enemyHp=Math.min(s.hp,enemyHp+Math.round(s.hp*.12));$('#arena').classList.add('evolving');$('#evolutionAlert').classList.add('danger');$('#evolutionAlert small').textContent='攻击提升，并可能发动暴虐连击！';announce('暴虐进化！','霸王龙恢复少量生命，攻击力提升');particles(350,70);setTimeout(()=>{setSprite('#enemyFighter','dino-2.png');$('.enemy-avatar').style.backgroundImage=`url('${AS+'dino-2.png'}')`;$('#enemyName').textContent='暴虐霸王龙 · 狂暴进化体';$('#arena').classList.remove('evolving');update();enemyTurn()},1450)}
function enemyTurn(){enemyTurns++;let s=stages[stage],bonus=evolved?2+Math.ceil(stage/2):0,d=s.atk[0]+Math.floor(Math.random()*(s.atk[1]-s.atk[0]+1))+bonus,combo=evolved&&enemyTurns%3===0;if(guard)d=Math.ceil(d/2);guard=false;$('#enemyFighter').classList.add(combo?'rage-attack':'attack');if(combo)announce('暴虐连击！','撑住这一轮！');setTimeout(()=>{$('#heroFighter').classList.add('hit');addFx('claw');hp-=d;update()},260);if(combo)setTimeout(()=>{hp-=Math.ceil(d*.42);addFx('claw second');particles(0,14);update()},610);setTimeout(()=>{$('#enemyFighter').classList.remove('attack','rage-attack');$('#heroFighter').classList.remove('hit');if(hp<=0)lose();else{busy=false;update()}},combo?1050:720)}
function win(){busy=false;let last=stage===3;let old=+(localStorage.getItem('bloko-stage')||0);localStorage.setItem('bloko-stage',Math.max(old,stage+1));$('#resultIcon').textContent=last?'🏆':'⭐';$('#resultTag').textContent=last?'终极任务完成':'战斗胜利';$('#resultTitle').textContent=last?'你是星际小英雄！':`${stages[stage].name} 已守住`;$('#resultText').textContent=last?`${hero.name}与你一起击退了终极暴虐霸王龙，四大能量核心全部安全！`:'配合得真棒！休整一下，下一关的霸王龙会更强。';$('#resultStars').textContent='★★★★'.slice(0,stage+1);$('#nextBtn').textContent=last?'再玩一次':'前往下一关';show('#resultScreen')}
function lose(){busy=false;$('#resultIcon').textContent='🛡️';$('#resultTag').textContent='别灰心';$('#resultTitle').textContent='能量核心正在修复';$('#resultText').textContent='这次只差一点！重新挑战时，多使用“守护充能”恢复生命，大招能量满了就立刻释放。';$('#resultStars').textContent='★★';$('#nextBtn').textContent='原地重新挑战';show('#resultScreen')}
function playMusic(){if(!music)return;$('#bgm').volume=.32;$('#bgm').play().catch(()=>{})}
$('#startBtn').onclick=()=>{stage=0;startStage()};$('#attackBtn').onclick=()=>playerMove('attack');$('#guardBtn').onclick=()=>playerMove('guard');$('#ultimateBtn').onclick=()=>playerMove('ult');$('#nextBtn').onclick=()=>{if(hp<=0)startStage();else{stage=stage===3?0:stage+1;startStage()}};$('#homeBtn').onclick=()=>show('#selectScreen');$('#soundBtn').onclick=()=>{music=!music;$('#soundBtn').textContent=music?'♫ 音乐开':'♫ 音乐关';music?playMusic():$('#bgm').pause()};renderHeroes();
